//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfModelFirst
{
    using System;
    
    public partial class Größen
    {
        public int LinkerFuß { get; set; }
        public int RechterFuß { get; set; }
    }
}
